### ISSUE TITLE
[Feature] Key binding to stop build.

### ISSUE THREAD

**Issue by arshapplied** [YaduAhuja/Code-Builder#1]
This will help us cancel the build , when accidentally input an infinite loop.

**Comment by YaduAhuja** [comment]
I am working on that feature by the time that is implemented you can use `Ctrl+c` to stop execution of code running in terminal

**Comment by arshapplied** [comment]
How Does the run in external terminal feature work on Mac ?

**Comment by YaduAhuja** [comment]
You Can just enable it in settings and then whenever you click the build button then an external terminal will open.

**Comment by arshapplied** [comment]
The option to run code in external window is just able to open the terminal app. It is not able to send the command to the app also , do you think it is possible for us to choose the external terminal app. Such as being able to send commands to iTerm app.

**Comment by YaduAhuja** [comment]
Check if you are using the latest version of the extension because on my friend's mac the latest version fixed that issue. Also, provide me your mac version if you are still having issues after updating.

iTerm support will also be added in coming weeks but currently only terminal is supported.

**Comment by arshapplied** [comment]
It works great now(on current Mac Os 12.0 Beta (21A5304g) ), looking forward to iTerm support.

**Comment by YaduAhuja** [comment]
I have added the Support to Bring terminal to the front of all windows Here is the Build: 

[code-builder-0.3.2.vsix.zip](https://github.com/YaduAhuja/Code-Builder/files/6988303/code-builder-0.3.2.vsix.zip)

It will be released this weekend if there are any bugs please let me know.

**Comment by arshapplied** [comment]
It was fixed on the latest update.

Can you also add something, that if a previous terminal window is minimized , unminimized it before showing the result. Because without this the code will run in the minimized terminal window, but the window will stay minimized.

**Comment by YaduAhuja** [comment]
It will take some time as my mac is damaged, but once it gets fixed I will add fix this issue.

**Comment by YaduAhuja** [comment]
I Have added the fix for terminal checkout in version 0.4.1. Also, Let me know of any other bugs.

**Comment by arshapplied** [comment]
For some reason , after the update i get the error on my mac "command 'code-builder.buildAndRun' not found" .

I do not believe that i have changed any of the settings. 

Also do you think , support to run R scripts can also be added.

**Comment by YaduAhuja** [comment]
Can you tell me the Version of VS code and Extension. 

Some Steps which may Fix extension : 
- Remove the extension and reinstall it again
- Go to extension settings and reset Every setting

R Support is added in 0.6.0 which will be pushed on 21st September

**Comment by arshapplied** [comment]
I got the error , on the latest update (of the extension) as of current time on vs code market place.

I also tried all of the above steps you mentioned to debug the problem.

![image](https://user-images.githubusercontent.com/68478842/133912891-930b1c65-8870-4299-8eed-6558d9b88f8e.png)

Here is my Vs code version details.

![image](https://user-images.githubusercontent.com/68478842/133912903-81e11c0e-6826-4080-8cfb-a511da2ac8a7.png)

**Comment by YaduAhuja** [comment]
Update your VS Code and then try again. It should fix the issue.

**Comment by arshapplied** [comment]
Ye'up that worked. It is working fine on version details :
Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:09:14.403Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by arshapplied** [comment]
For some reason the extension is giving the same error  again ```command 'code-builder.buildAndRun' not found```

Extension version is 0.6.0

Vs code version is :

Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:09:14.403Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by YaduAhuja** [comment]
Can You provide me the console data. it is enabled through `Help -> Toggle Developer Tools`.
Also check if only BuildAndRun is not working or every code builder command is not found.

**Comment by arshapplied** [comment]
Sometimes it is working and sometimes it is not working , i have added the console data here.

![image](https://user-images.githubusercontent.com/68478842/134450994-025e948b-40d7-4ad6-8186-af36ff70f3bf.png)

![image](https://user-images.githubusercontent.com/68478842/134451009-cc56e3db-819c-4f2f-a760-4a76104ff07c.png)

![image](https://user-images.githubusercontent.com/68478842/134451022-9d71b260-efaa-4a71-8aa7-d7aefbad9816.png)

**Comment by YaduAhuja** [comment]
There are some files missing in your installation of VS Code that is required for extension Host to Work. See at the Starting of your first screenshot. 
To Fix this uninstall this VS Code and delete the `.vscode` folder from your `Users` directory and then reinstall VS Code.

**Comment by arshapplied** [comment]
Thanks for helping, i tried to uninstall and delete the /vscode folder. I still get the issue of FILE not found . This seems to be a vscode issue. Other than that your extension seems to be working fine.

I will try to figure this out myself.

Also any update , on when can we run in iTerm (External terminal) ?

**Comment by YaduAhuja** [comment]
iTerm2 support will be added in the build 0.7.0.

**Comment by arshapplied** [comment]
Hey with the new update, the item2 app still does not work. Just to be on the same page , i am trying to use  terminal emulator from this website : https://iterm2.com.

It is giving me these errors.

![image](https://user-images.githubusercontent.com/68478842/135044058-47fa637e-60a2-41a5-8622-8ab9b2dee60c.png)

This is the info of the app , on mac 

![image](https://user-images.githubusercontent.com/68478842/135044220-9846b975-93db-4860-badf-935f6a7e30bd.png)

**Comment by YaduAhuja** [comment]
I have released a hotfix for that check your marketplace for updates and then try again.
use the `iTerm.app` in your `terminal.external.osxExec` in preferences

**Comment by arshapplied** [comment]
On version 0.6.2 iTerm works great.
