### ISSUE TITLE
Support for m1 Mac 

### ISSUE THREAD

**Issue by arshappleid** [YaduAhuja/Code-Builder#4]
Just wondering if you will be releasing support for m1 Mac ??

These are my version details : 
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:00:52.911Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 21.1.0

**Comment by YaduAhuja** [comment]
I am not sure what kind of support are you requesting on m1 mac.

**Comment by YaduAhuja** [comment]
I don't have m1 mac, so i cannot test it on that machine but what are your errors if you post them here i will be able to resolve it.

**Comment by arshappleid** [comment]
I get this error , when trying to install the extension.
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/68478842/148982784-56399452-2126-4836-b36a-ce1c8a0ef576.png">

**Comment by arshappleid** [comment]
Never mind , that was the old version of vs code. That might have been the reason, I will close the issuee.
