### ISSUE TITLE
[Feature] Support to run binary code in ".asm" files/

### ISSUE THREAD

**Issue by arshappleid** [YaduAhuja/Code-Builder#5]
Can you add the support to run binary code  (MIPS) , which is taught in most schools.

Source code at  : http://courses.missouristate.edu/KenVollmar/MARS/

To run the .asm file this is the command that works : "java -jar Mars4_5.jar 10000 $fileName"  , assuming the Mars4_5.jar file is placed in the same repo. Which is downloadable from the above link. Also java needs to be installed.

The description of the terminal commands can be found here : https://courses.missouristate.edu/kenvollmar/mars/Help/Help_4_1/MarsHelpCommand.html .

**Comment by YaduAhuja** [comment]
You can modify the executor map to add support for mips. Add below line in executor map for run support.
` "mips": "java -jar Mars45.jar $fileName" `

Add `mips` to the extension settings -> language selector to show run button in asm files.

Note : VSCode natively does not provide language identifiers for the mips and assembly to add that you will need the language support. I used the language support from the extension **MIPS Support** by **kdarkhan**.
